### ISSUE TITLE
API查询出的天气预报数据与SDK不同

### ISSUE THREAD

**Issue by JunL90s** [heweather/dev-site#1]
url参数如下https://free-api.heweather.net/s6/weather/forecast?location=116.5522579101445,39.89687524028301&key=【key】，该API只能查出北京未来3天的天气预报数据，而同样的坐标用安卓SDK能查到未来7天的数据

**Comment by JunL90s** [comment]
https://free-api.heweather.net/s6/weather/forecast?location=116.5522579101445,39.89687524028301&key=【key】

**Comment by mitaosi** [comment]
因为安卓SDK给的默认用户权限是认证个人开发者，普通个人用户API只给3天
